### ISSUE TITLE
Remove the 'view password' button.

### ISSUE THREAD

**Issue by awnumar** [spaceshuttl/coffer#9]
Instead allow users to click on the hidden password to un-hide it, and vice-versa.

**Comment by tobbbles** [comment]
Would this appear obvious and intuitive to users? Personally I don't believe it would

**Comment by awnumar** [comment]
It could be made intuitive. On the other hand, having three buttons is just clutter, and this is even more so noticeable on smaller screens.

I mean the view password function isn't even critical when you have the copy to clipboard button.

**Comment by tobbbles** [comment]
Because Coffer can store sentences (I'm unsure if there's a length limit, actually) - we may want to keep coffer multi-functional, meaning 'secrets' can be stored too. I think it's a bad idea to not have a way to reveal the secrets/passwords.

A tooltip could be added next to the 'password' table header explaining to click on the passwords to show them? I'm undecided as of yet, it'd be nice to wait for feedback from users
